name: mobile_app
description: A ride-hailing mobile app (Passenger &amp; Driver) Flutter frontend.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 &lt;4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  go_router: ^14.2.0
  flutter_secure_storage: ^9.2.2
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/